export const ASSIN = [
  {
    className: "BIOLOGY_1_HONORS",
    name: "Pig Practical",
    term: "Q1",
    category: "Major",
    grade: "96",
    outOf: 100,
    dueDate: "05/09/25",
    artificial: false,
  },
  {
    className: "BIOLOGY_1_HONORS",
    name: "Pig Disection #1",
    term: "Q1",
    category: "Labs",
    grade: "95",
    outOf: 100,
    dueDate: "05/06/25",
    artificial: false,
  },
  {
    className: "BIOLOGY_1_HONORS",
    name: "Biodiv. Threats",
    term: "Q2",
    category: "Daily",
    grade: "100",
    outOf: 100,
    dueDate: "04/10/25",
    artificial: false,
  },
  {
    className: "AP_PRECALCULUS",
    name: "Test Intro to Trig",
    term: "SM1",
    category: "Major",
    grade: "89",
    outOf: 100,
    dueDate: "04/10/25",
    artificial: false,
  },
];
